# Developers should run 'pre-commit install' in this repo.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: format
    name: Format
    entry: aspect run //tools/format:format
    language: system
    types: [text]
# Lint for starlark code.
# Special case since rules_lint doesn't want to require that BUILD files are
# listed as the srcs of some *_library target.
- repo: https://github.com/keith/pre-commit-buildifier
  rev: 6.4.0
  hooks:
    - id: buildifier-lint
